// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Garage5testTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void garage5test() {
    driver.get("https://qauto2.forstudy.space/");
    driver.manage().window().setSize(new Dimension(1328, 860));
    driver.findElement(By.xpath("//button[contains(.,\'Sign In\')]")).click();
    driver.findElement(By.id("signinEmail")).sendKeys("Fusionbreak6@hillel.com");
    driver.findElement(By.id("signinPassword")).sendKeys("Na131415");
    driver.findElement(By.id("remember")).click();
    driver.findElement(By.xpath("//button[contains(.,\'Login\')]")).click();
    driver.findElement(By.xpath("//*[contains(text(),\'Fuel expenses\')]")).click();
    driver.findElement(By.id("carSelectDropdown")).click();
    driver.findElement(By.xpath("//li[2]")).click();
    driver.findElement(By.xpath("//button[contains(.,\'Add an expense\')]")).click();
    {
      List<WebElement> elements = driver.findElements(By.xpath("//div/div/button/span"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.id("addExpenseLiters")).click();
    driver.findElement(By.id("addExpenseMileage")).click();
    driver.findElement(By.id("addExpenseMileage")).sendKeys("160");
    driver.findElement(By.id("addExpenseLiters")).click();
    driver.findElement(By.id("addExpenseLiters")).sendKeys("10");
    driver.findElement(By.id("addExpenseTotalCost")).click();
    driver.findElement(By.id("addExpenseTotalCost")).sendKeys("10");
    driver.findElement(By.xpath("//button[2]")).click();
    driver.findElement(By.id("userNavDropdown")).click();
    driver.findElement(By.xpath("//button[contains(.,\'Logout\')]")).click();
    driver.close();
  }
}
